### List all Messages 
GET http://localhost:3000/messages

### Create a new message
POST http://localhost:3000/messages
content-type: application/json
{
    "content": "Hello Slavo"
}

### GEt a message
GET http://localhost:3000/messages/1231243